require("stefan.plugins-setup")
require("stefan.core.options")
require("stefan.core.keymaps")
require("stefan.core.colorscheme")
require("stefan.plugins.comment")
require("stefan.plugins.nvim-tree")
require("stefan.plugins.lualine")
require("stefan.plugins.telescope")
require("stefan.plugins.nvim-cmp")
require("stefan.plugins.lsp.mason")
require("stefan.plugins.lsp.lspsaga")
require("stefan.plugins.lsp.lspconfig")
require("stefan.plugins.lsp.null-ls")
require("stefan.plugins.autopairs")
require("stefan.plugins.treesitter")
require("stefan.plugins.auto-session")
require("stefan.plugins.session-lens")
require("stefan.plugins.nightfox")

-- OLD CONFIGURATION
-- require("backup-config.plugins")
-- require("backup-config.settings")
-- require("backup-config.keymaps")
-- require("backup-config.lsp")
-- require("backup-config.plugins.nvim-tree")
-- require("backup-config.plugins.treesitter")
-- require("backup-config.plugins.neoformat")
-- require("backup-config.plugins.comment")
-- require("backup-config.plugins.vimspector")
-- require("backup-config.plugins.autopairs")
-- require("backup-config.plugins.autotag")
-- require("backup-config.plugins.auto-session")
-- require("backup-config.plugins.luasnip")
-- require("backup-config.plugins.colorizer")
-- require("backup-config.plugins.lualine")
-- require("backup-config.plugins.nightfox")
-- require("backup-config.plugins.surround")
